custom_tags:
    rawhtml:
        template: "@ibexadesign/ezrichtext/custom_tags/rawhtml.html.twig"
        icon: '/bundles/ibexaicons/img/all-icons.svg#information'
        attributes:
            name:
                type: string
