
system:
    admin_group:
        fieldtypes:
            ezrichtext:
                custom_tags: [rawhtml]
                toolbar:
                    custom_tags_group:
                        buttons:
                            rawhtml:
                                priority: 5
